
spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
  output:
    ansi:
      enabled: always